adapter: github
issue_tracker: github
pr_type: ['feature', 'bugfix', 'refactor', 'tests', 'remove', 'style', 'documentation', 'security']
table-pr:
    fixed_tickets: ['Fixed Tickets', '']
    license: ['License', 'GPL-3.0+']
base: master
